# .github/workflows/build-and-approval.yml
name: Build and Approval

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven
      - name: Build the Docker image
        run: |
          mvn --version
          mvn clean install
          docker build . --file Dockerfile --tag sp-customer:latest
          docker images

  approval:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const result = await github.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: "Approval Needed for Docker Push",
              body: "Please approve this issue to proceed with deployment."
            })
            core.setOutput("issue_number", result.data.number)

      - name: Wait for approval
        id: wait-for-approval
        uses: actions/manual-approval@v1
        with:
          approvers: suyog3839
          minimum-approvals: 1
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Trigger Deployment Workflow
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'deployment.yml',
              ref: 'main'
            })
