name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin' # You can use 'zulu' or other distributions if you prefer
        java-version: '17'
        cache: maven
    - name: Build the Docker image
      run: |
        mvn --version
        mvn clean install
        docker build . --file Dockerfile --tag sp-customer:$(date +%s)
  push:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: trstringer/manual-approval@v1
        with:
            secret: ${{ github.TOKEN }}
            approvers: suyog3839
            minimum-approvals: 1
            issue-title: "push docker "
            issue-body: "Please approve or deny the deployment of version v1.3.5."
            exclude-workflow-initiator-as-approver: false
            additional-approved-words: ''
            additional-denied-words: ''
      - name: Log in to Docker Hub
        run: echo "test done1"
