name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin' # You can use 'zulu' or other distributions if you prefer
        java-version: '17'
    - name: Build the Docker image
      run: |
        mvn --ers
        mvn clean install
        docker build . --file Dockerfile --tag sp-customer:$(date +%s)
