name: Docker Image CI

on:
  push:
    branches: [ "main","develop" ]
  pull_request:
    branches: [ "main","develop" ]
  workflow_dispatch:

jobs:

  DeployDev:
    name: deploy to dev
    if: github.event.ref == 'refs/heads/develop'
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: dev
      url: 'localhost:8080'
    steps:
      - name: dev deploy b
        run: echo 'deploy to dev'
  DeployUat:
    name: deploy to uat
    if: github.event.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: uat
      url: 'localhost:8080'
    steps:
      - name: uat deploy
        run: echo 'deploy to uat'
  DeployProd:
    name: deploy to prod
    needs: DeployUat
    runs-on: ubuntu-latest
    environment:
      name: prod
      url: 'localhost:8080'
    steps:
      - name: prod deploy
        run: echo 'deploy to prod'
